# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ms_emotionRecognition_pb2 as ms__emotionRecognition__pb2


class EmotionRecognitionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Inference = channel.unary_unary(
                '/emotionRecognition.EmotionRecognitionService/Inference',
                request_serializer=ms__emotionRecognition__pb2.EmotionRecognitionRequest.SerializeToString,
                response_deserializer=ms__emotionRecognition__pb2.EmotionRecognitionInferenceReply.FromString,
                )


class EmotionRecognitionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Inference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmotionRecognitionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Inference': grpc.unary_unary_rpc_method_handler(
                    servicer.Inference,
                    request_deserializer=ms__emotionRecognition__pb2.EmotionRecognitionRequest.FromString,
                    response_serializer=ms__emotionRecognition__pb2.EmotionRecognitionInferenceReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emotionRecognition.EmotionRecognitionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmotionRecognitionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Inference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/emotionRecognition.EmotionRecognitionService/Inference',
            ms__emotionRecognition__pb2.EmotionRecognitionRequest.SerializeToString,
            ms__emotionRecognition__pb2.EmotionRecognitionInferenceReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
